version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    hostname: localhost
    ports:
      - 3333:3000
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/bimp_chat'
      PORT: 3000

  postgres:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    env_file:
      - docker.env
